### ISSUE TITLE
Add dark mode !!

### ISSUE THREAD

**Issue by Anudeep-313** [Anudeep-313/mini-project#1]
- Add dark mode to this website.
- Add beautiful sliding toggle switch button to enable dark mode.(optional improvement)

**Comment by ch3ber** [comment]
can you assign the issue to me?

**Comment by Anudeep-313** [comment]
> can you assign the issue to me?

Yeah, Proceed with it 👍

**Comment by Samriddh2703** [comment]
can you assign the issue to me?

**Comment by Anudeep-313** [comment]
> can you assign the issue to me?

Go ahead.

**Comment by ch3ber** [comment]
finished I just have to do the pull request

**Comment by Anudeep-313** [comment]
> finished I just have to do the pull request

Great!! @ch3ber.

**Comment by ch3ber** [comment]
@Anudeep-313 check the pull request and give me your feedback

**Comment by Pranshu1902** [comment]
@Anudeep-313 Please assign this issue to me, I would love to contribute to it

**Comment by Pranshu1902** [comment]
@Anudeep-313 Please assign this issue to me, I would love to contribute to it

**Comment by Anudeep-313** [comment]
Instead of a simple toggle theme button on the nav bar, It would be great if someone can upgrade it to a sliding toggle button.

**Comment by Soumyajit2825** [comment]
@Anudeep-313 I would like to contribute in your project..As you say upgrading to a sliding toggle button..I would like to go through it..Can you please assign it to me????
