### ISSUE TITLE
Add descriptive text in README file about the project

### ISSUE THREAD

**Issue by Stronkness** [Anudeep-313/mini-project#13]
I feel that some kind of text for the project would be nice. A small description how to run it and what it does would be good.
Is this of interest?

**Comment by Anudeep-313** [comment]
Sure, Go ahead!

**Comment by Stronkness** [comment]
How do you start it though? I know python and React, but cant figure out in this project

**Comment by Anudeep-313** [comment]
> How do you start it though? I know python and React, but cant figure out in this project

This website is just the frontend of the project.
Just add the a small description as it is in the website.

**Comment by Stronkness** [comment]
A description regarding the app right?
