### ISSUE TITLE
Required better UI Design

### ISSUE THREAD

**Issue by harshit-maheshwari** [Anudeep-313/mini-project#14]
I checked the website and found out there are lot of things which can be added to the UI, being UI/UX designer I know what the UI should look like.
I want to do changes in the button styling, background, and navigation bar. 
There are other changes too which I want to add to the UI

**Comment by pranshuj73** [comment]
would like to take this up!

**Comment by Anudeep-313** [comment]
@pranshuj73 @harshit-maheshwari It would be great if y'all can improve the design of this project, Go ahead.                     
The maintainers will review the changes and approve accordingly.

**Comment by pranshuj73** [comment]
> @pranshuj73 @harshit-maheshwari It would be great if y'all can improve the design of this project, Go ahead. The maintainers will review the changes and approve accordingly.

Sounds perfect!

**Comment by neeraj542** [comment]
I would like to work on this issue

**Comment by Anudeep-313** [comment]
Thank you everyone for your contribution.
