### ISSUE TITLE
Adding Custom Gradient ScrollBar

### ISSUE THREAD

**Issue by aakashraj01** [Anudeep-313/mini-project#18]
Hey @Anudeep-313 I checked the website and found according to color scheme and button gradient colors , the scroll bar also needs betterment.
So I want to add a custom gradient color scrollbar .
Can you assign this issue to me under Hacktoberfest'22 :) ?

**Comment by Anudeep-313** [comment]
Sure Go ahead!! 👍

**Comment by aakashraj01** [comment]
Hey @Anudeep-313 I have opened the PR for this issue .Please review and merge it. Hoping you like my work!!
