### ISSUE TITLE
Create a neat SingUp page.

### ISSUE THREAD

**Issue by Anudeep-313** [Anudeep-313/mini-project#2]
- build a simple signup page.
- Make it look cool.

**Comment by aaushitiwari** [comment]
@Anudeep-313 do you only want the front-end part of the signup page?

**Comment by bhavyajshah** [comment]
Hello @Anudeep-313 Please provide me this task so I can do help you very easily.

**Comment by aditi10701** [comment]
I want to work on this project kindly assign me the same. I have made similar front end projects and an build the same. @Anudeep-313

**Comment by Anudeep-313** [comment]
@aaushitiwari Yes i only need the frontend part.

**Comment by Anudeep-313** [comment]
> @Anudeep-313 do you only want the front-end part of the signup page?

yes i only need the frontend.

**Comment by Anudeep-313** [comment]
> Hello @Anudeep-313 Please provide me this task so I can do help you very easily.

Take up task, I'll approve the best one.

**Comment by Anudeep-313** [comment]
> I want to work on this project kindly assign me the same. I have made similar front end projects and an build the same. @Anudeep-313

sure!!, You can work on it.

**Comment by Anudeep-313** [comment]
@bhavyajshah @aditi10701 @aaushitiwari Y'all start working on it and request a PR, i'll suggest if any improvements are required.

**Comment by iamkelv** [comment]
can you assign the issue to me? so that you can review my code and see

**Comment by Samriddh2703** [comment]
can you assign the issue to me?

**Comment by Pranshu1902** [comment]
@Anudeep-313 Please assign this issue to me, I would love to contribute to it

**Comment by Pranshu1902** [comment]
@Anudeep-313 Please assign this issue to me, I would love to contribute to it

**Comment by vbindal** [comment]
assign it to me I will make it for you

**Comment by avatar-10000** [comment]
I am a good frontend developer, I would like to take this up.

**Comment by aditi10701** [comment]
> @bhavyajshah @aditi10701 @aaushitiwari Y'all start working on it and request a PR, i'll suggest if any improvements are required.

I have made the necessary changes and raised a PR

**Comment by bhavyajshah** [comment]
Hello, @Anudeep-313 I have created a PR for the Signup Page Please check it out and If you like then please accept it.
