### ISSUE TITLE
Bug in Footer and remove extra padding

### ISSUE THREAD

**Issue by bhuvan-tech** [Anudeep-313/mini-project#25]
![DATAVIS - Brave 2022-10-03 08-31-58_Trim](https://user-images.githubusercontent.com/74106022/193494809-050e9108-2993-4958-bd74-b6aea04be1ed.gif)

**Comment by bhuvan-tech** [comment]
@pranshuj73 could you address this issue?

**Comment by vbindal** [comment]
okay i will fix it assign it to me

**Comment by Anudeep-313** [comment]
> okay i will fix it assign it to me

We haven't merged @pranshuj73 PR yet, you won't able to fix it until we merge it to main branch.
Your changes to CONTRIBUTING.md file are good, close that PR and request another PR for the same, it has some conflicts.

**Comment by vbindal** [comment]
okay
