### ISSUE TITLE
Help required in creating contribution rules (Documentation).

### ISSUE THREAD

**Issue by Anudeep-313** [Anudeep-313/mini-project#3]
- Add the mandatory contribution rules to the Readme.

**Comment by Anudeep-313** [comment]
> assign this to me

Go ahead.

**Comment by vbindal** [comment]
assign this to me

**Comment by Stronkness** [comment]
If you would like, you could assign this to me and il upload something in the coming 30 minutes

**Comment by Stronkness** [comment]
I have pushed a PR for this, please take a look
#11
