### ISSUE TITLE
Update toggle button

### ISSUE THREAD

**Issue by sahilrajput18** [Anudeep-313/mini-project#35]
i wanna enhance the toggle button with moon and sun emoji to your project and make a contribution to hacktoberfest

**Comment by A1Kumari** [comment]
can I work on this issue

**Comment by sahilrajput18** [comment]
> can I work on this issue
> 

yet to be assigned by the maintainer :/

**Comment by Anudeep-313** [comment]
the website already has moon and sun emoji toggle button

**Comment by sahilrajput18** [comment]
@Anudeep-313 oh when i raised the issue it wasn't there so oops nvm , anything you suggest that i can improve of as an contribution?

**Comment by Anudeep-313** [comment]
> @Anudeep-313 oh when i raised the issue it wasn't there so oops nvm , anything you suggest that i can improve of as an contribution?

Try to make this project readme attractive if possible, also suggest if any improvements can be made in the website.
