### ISSUE TITLE
Readme.md could be updated and enhanced

### ISSUE THREAD

**Issue by A1Kumari** [Anudeep-313/mini-project#39]
The readme.md file just shows the project snippet and doesn't mention much about how the project works or what idea is the project built upon  what are the tech stalks used and many more such things could be used to tell

**Comment by Anudeep-313** [comment]
Add the tech stack used in this project to the readme.

**Comment by itsmetheom** [comment]
#48  would like to work on this issue, please assign it to me!

**Comment by Anudeep-313** [comment]
Try Replacing the text with icons, I think logos of the tech used look cooler than the text.
Try to work on it if possible.

**Comment by itsmetheom** [comment]
alright working on it
