### ISSUE TITLE
Add some cool Css effects to footer of the webpage.

### ISSUE THREAD

**Issue by Anudeep-313** [Anudeep-313/mini-project#5]
- The footer of this webpage contains the names of this project creators.
- Add any css effect to make it cool, Example : Button pop effect on hover

**Comment by yesimhozman** [comment]
Hi, I would like to contribute, can you assign it to me?

**Comment by Anudeep-313** [comment]
> Hi, I would like to contribute, can you assign it to me?

Thank you for your interest to contribute to this project, I have assigned this issue to you.

**Comment by Samriddh2703** [comment]
can you assign the issue to me?

**Comment by dhaneshragu** [comment]
Can you assign this to me?

**Comment by IpsitaSenapati** [comment]
I would like to work on this. Please assign it to me.

**Comment by Anudeep-313** [comment]
This issue is closed ........if there is any room for improvement, comment it.... I'll reopen the issue.
