### ISSUE TITLE
Add both Github and Linkedln IDs of Developers

### ISSUE THREAD

**Issue by soustab10** [Anudeep-313/mini-project#54]
In the footer section, on hover have icons with links to their github and linkedln ids, consistent with the present theme of the website.
If approved, I would like to work on this issue.

**Comment by Anudeep-313** [comment]
Yeah go ahead.

**Comment by soustab10** [comment]
Are you planning to add more developers to the footer section?
And please provide me the github handles of the current developers. Thank you.

**Comment by Anudeep-313** [comment]
Anudeep - https://github.com/Anudeep-313
Bhuvan - https://github.com/bhuvan-tech
Bhanu prakash - https://github.com/BhanuPrakash056
Angaj - https://github.com/ANGAJ2001
