### ISSUE TITLE
Modification of footer

### ISSUE THREAD

**Issue by aditi10701** [Anudeep-313/mini-project#56]
Footer can be modified
reference image.
Kindly assign me this issue.
![image](https://user-images.githubusercontent.com/98349669/194937182-98832cde-2116-48d0-b61d-7c4c08c89d0d.png)

**Comment by shreyapd666** [comment]
please assign me

**Comment by Anudeep-313** [comment]
Thank you for your interest, I don't think we need a footer for this website. 
When it's required, i will reopen the issue and assign it you.

**Comment by Anudeep-313** [comment]
> Thank you for your interest, I don't think we need a footer for this website. When it's required, i will reopen the issue and assign it you.

@aditi10701
