### ISSUE TITLE
Add the top contributors in the Readme.

### ISSUE THREAD

**Issue by yasirobai99** [Anudeep-313/mini-project#6]
In the Readme, I will add the top contributors and project admin

**Comment by Anudeep-313** [comment]
Yeah that would be cool!!.
Go ahead.

**Comment by KanishkDadhich** [comment]
Heyy @Anudeep-313 . I can see that this website doesn't have a Favicon. It would be quite captivating if this had one.
And I would like to work on this under Hacktoberfest.

**Comment by Anudeep-313** [comment]
> Heyy @Anudeep-313 . I can see that this website doesn't have a Favicon. It would be quite captivating if this had one. And I would like to work on this under Hacktoberfest.

Sure go ahead 👍

**Comment by KanishkDadhich** [comment]
So shall I add another issue for this?

**Comment by yasirobai99** [comment]
Hey I have done it So do I need to do any changes or I can make the PR
![Screenshot from 2022-10-03 00-17-33](https://user-images.githubusercontent.com/83706868/193470984-65d0aae2-a706-4e0a-9b97-4c9007c14d5f.png)

**Comment by Anudeep-313** [comment]
it's cool, proceed with the PR.

**Comment by Anudeep-313** [comment]
> So shall I add another issue for this?

sure!!
