### ISSUE TITLE
make the about button glow like others on the homepage

### ISSUE THREAD

**Issue by yuvraj-wale** [Anudeep-313/mini-project#61]
currently the about button is not glowing when we shower on it like the other buttons (home, sales, shipping, products). so add glow effect to about button on home page in header navber section.

**Comment by yuvraj-wale** [comment]
this bug has been fixed with the PR #62

**Comment by Anudeep-313** [comment]
Great!! thank you for your contribution, Me and my team have decided to remove the about page from the website.
Anyway we are open for suggestions, If you have something else to contribute please go ahead and open an issue.
